version: "3.8"

services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:latest
    container_name: cobalt-api
    restart: unless-stopped
    environment:
      API_URL: http://cobalt:9000
      API_NAME: "Bookmark Media Downloader"
      CORS_WILDCARD: "true"
      CORS_URL: "*"
    ports:
      - "9002:9000"
    networks:
      - webapp
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/serverInfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  webapp:
    external: true
    name: webapp
