"""simplify schema remove summarization

Revision ID: bec1699553ed
Revises: fc370d8b87e9
Create Date: 2025-11-20 22:23:01.753842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec1699553ed'
down_revision = 'fc370d8b87e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_session', sa.Column('save_to_database', sa.Boolean(), nullable=False), schema='crawler')
    op.add_column('crawl_session', sa.Column('export_to_file', sa.Boolean(), nullable=False), schema='crawler')
    op.drop_column('crawl_session', 'direct_import', schema='crawler')
    op.drop_column('crawl_session', 'enable_summarization', schema='crawler')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_session', sa.Column('enable_summarization', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='crawler')
    op.add_column('crawl_session', sa.Column('direct_import', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='crawler')
    op.drop_column('crawl_session', 'export_to_file', schema='crawler')
    op.drop_column('crawl_session', 'save_to_database', schema='crawler')
    # ### end Alembic commands ###
