"""initial schema

Revision ID: fc370d8b87e9
Revises: 
Create Date: 2025-11-20 22:18:52.279324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc370d8b87e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_session',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('bookmarks_processed', sa.Integer(), nullable=True),
    sa.Column('direct_import', sa.Boolean(), nullable=False),
    sa.Column('enable_summarization', sa.Boolean(), nullable=False),
    sa.Column('output_file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    schema='crawler'
    )
    op.create_table('twitter_crawl_checkpoint',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('last_tweet_id', sa.String(length=255), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=False),
    sa.Column('bookmarks_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='crawler'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_crawl_checkpoint', schema='crawler')
    op.drop_table('crawl_session', schema='crawler')
    # ### end Alembic commands ###
